server:
  port: 80
spring:
  application:
    name: student-manager-app
  profiles:
    active: @spring.profiles.active@

# Health check
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  health: # config for EKS
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  prometheus:
    metrics:
      export:
        step: 5s
        enabled: true

jwt:
  timeout: 360000
  timeoutRefresh: 10800000
  securityKey: 2dae84f846e4f4b158a8d26681707f4338495bc7ab68151d7f7679cc5e56202dd3da0d356da007a7c28cb0b780418f4f3246769972d6feaa8f610c7d1e7ecf6a

# Logging
#logging:
#  level:
#    root: INFO
#    web: OFF
#    org.springframework: INFO
#    org.apache: OFF
#    kafka: OFF
